"""empty message

Revision ID: 43d3ad75660f
Revises: 
Create Date: 2021-08-25 10:43:58.672044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d3ad75660f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('image', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options', 'image')
    # ### end Alembic commands ###
